j_programowania_project_test:
    path: /test
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:test

j_programowania_project_cars_list:
    path: /oferta
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:carsList

j_programowania_project_generator:
    path: /generator
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:initializeDB

j_programowania_project_reservation:
    path: /zrob rezerwacje
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:doReservation
