j_programowania_project_homepage:
    path: /hello/{name}
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:index

j_programowania_project_test:
    path: /test
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:test
