j_programowania_project:
    resource: "@JProgramowaniaProjectBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login
    defaults:
        _controller: JProgramowaniaProjectBundle:Security:login

login_check:
    pattern: /login_check

logout:
    path: /logout

start_dotpay:
    path: /start/dotpay
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:startDotpay 

perfom_dotpay_payment:
    path: /perform/dotpay/payment
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:performDotpayPayment 

confirm_payment:
    path: /confirm/payment
    defaults:
        _controller: JProgramowaniaProjectBundle:Default:confirm
