security:
    firewalls:
        default:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path: /logout
                target: /
            provider: our_db_provider

    access_control:
        - { path: ^/klient, roles: ROLE_USER }

    providers:
        our_db_provider:
            entity:
                class: JProgramowaniaProjectBundle:User
                property: username

    encoders:
        JProgramowania\ProjectBundle\Entity\User:
            algorithm: bcrypt